exports.seed = async function (knex) {
  await knex("product").insert([
    // SMASH
    {
      name: "Smash Beer Burger",
      description: "Lanches",
      ingredient: "Burguer 100g bovino e queijo.",
      price: 12.9,
      additional: "1,2,3",
      image: "s1.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Smash Salada Berr Burger",
      description: "Lanches",
      ingredient: "Burger 100g bovino, queijo e salada.",
      price: 15.9,
      additional: "1,2,3",
      image: "s2.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Smash Beer Burger Bacon",
      description: "Lanches",
      ingredient: "Burger bovino 100g, queijo e bacon.",
      price: 17.9,
      additional: "1,2,3",
      image: "s3.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Smash Beer Double Burger",
      description: "Lanches",
      ingredient: "2 burguers bovino 100g, 2 queijos e bacon.",
      price: 25.9,
      additional: "1,2,3",
      image: "s4.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Smash American Beer",
      description: "Lanches",
      ingredient:
        "Pão, Smash Burger 100 Gr, cheddar cremoso e picles de pepino.",
      price: 19.9,
      additional: "1,2,3",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 59,
      visibleApp: true,
    },

    // Hamburguers
    {
      name: "Cheese Burger",
      description: "Lanches",
      ingredient: "Pão, burguer artesanal bovino 200g e queijo.",
      price: 19.8,
      additional: "1,2,3",
      image: "h5.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Tradicional Beer",
      description: "Lanches",
      ingredient: "Burguer artesanal bovino 200g, queijo e bacon.",
      price: 32.8,
      additional: "1,2,3",
      image: "h6.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Relish Beer",
      description: "Lanches",
      ingredient:
        "Pão, burguer artesanal bovino 200g, queijo, bacon, relish de pepino agridoce",
      price: 27.8,
      additional: "1,2,3",
      image: "h7.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Salada Beer",
      description: "Lanches",
      ingredient:
        "Pão, burguer artesanal bovino 200g, queijo, alface, tomate e cebola roxa.",
      price: 21.8,
      additional: "1,2,3",
      image: "h8.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Club",
      description: "Lanches",
      ingredient:
        "Pão, burguer 200g, queijo, bacon, cebola caramelizada com açúcar mascavo.",
      price: 27.8,
      additional: "1,2,3",
      image: "h9.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Beer Crocante",
      description: "Lanches",
      ingredient: "Burger 200g, queijo, bacon, cebola crispy.",
      price: 29.8,
      additional: "1,2,3",
      image: "h10.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Double Killer",
      description: "Lanches",
      ingredient:
        "Pão, 2 burguer 200g, queijo duplo, bacon duplo, alface e tomate.",
      price: 35.8,
      additional: "1,2,3",
      image: "h12.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Texas Beer",
      description: "Lanches",
      ingredient:
        "Pão, burguer 200g, queijo, alface, tomate, onion rings e molho barbecue.",
      price: 28.8,
      additional: "1,2,3",
      image: "h13.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Cancún Beer",
      description: "Lanches",
      ingredient:
        "Pão, burguer 200g, queijo, bacon, geleia de pimenta, cebola crispy.",
      price: 30.8,
      additional: "1,2,3",
      image: "h14.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Catu Beer",
      description: "Lanches",
      ingredient: "Burger 200g, queijo, catupiry, alho frito.",
      price: 27.8,
      additional: "1,2,3",
      image: "h15.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Triple Killer",
      description: "Lanches",
      ingredient:
        "Pão, 3 burger 200g, triplo queijo, triplo bacon, alface, tomate e cebola roxa.",
      price: 43.8,
      additional: "1,2,3",
      image: "h16.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Manhattan Beer",
      description: "Lanches",
      ingredient:
        "Pão, carne 200 Gr , cheddar cremoso com pedaços de bacon e cebola caramelizada no açúcar mascavo.",
      price: 29.9,
      additional: "1,2,3",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Brooklyn Beer",
      description: "Lanches",
      ingredient: "Carne 200 Gr, pedaços de bacon cheddar cremoso.",
      price: 27.9,
      additional: "1,2,3",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Minas Beer",
      description: "Lanches",
      ingredient:
        "Pão, Burger 200 gr, queijo prato, alface, tomate e  pedaços de bacon com molho 4 queijos.",
      price: 29.9,
      additional: "1,2,3",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 59,
      visibleApp: true,
    },

    // Pasteis
    {
      name: "Mini Pastel",
      description: "Pasteis",
      ingredient: "",
      price: 26.9,
      additional: "",
      image: "c3.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 3,
      measureUnid_id: 59,
      visibleApp: true,
    },

    // Bebidas
    {
      name: "Suco Del Valle Uva",
      description: "Bebidas",
      ingredient: "",
      price: 4.5,
      additional: "",
      image: "p7.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Suco Del Valle Pêssego",
      description: "Bebidas",
      ingredient: "",
      price: 4.5,
      additional: "",
      image: "p13.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Suco Del Valle Maracujá",
      description: "Bebidas",
      ingredient: "",
      price: 4.5,
      additional: "",
      image: "p15.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Energético Monsters",
      description: "Bebidas",
      ingredient: "",
      price: 10,
      additional: "",
      image: "p16.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Água Crystal com gás",
      description: "Bebidas",
      ingredient: "",
      price: 3.5,
      additional: "",
      image: "p8.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Água Crystal sem gás",
      description: "Bebidas",
      ingredient: "",
      price: 3,
      additional: "",
      image: "p14.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Coca Cola 1 Litro",
      description: "Bebidas",
      ingredient: "",
      price: 8,
      additional: "",
      image: "p10.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Coca Cola 600ml",
      description: "Bebidas",
      ingredient: "",
      price: 6,
      additional: "",
      image: "p20.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Sprite Lemon Fresh",
      description: "Bebidas",
      ingredient: "",
      price: 5,
      additional: "",
      image: "p9.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Shweppes Citrus Lata",
      description: "Bebidas",
      ingredient: "",
      price: 5,
      additional: "",
      image: "p17.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Shweppes Tônica Lata",
      description: "Bebidas",
      ingredient: "",
      price: 4.5,
      additional: "",
      image: "p21.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Kuat Lata 350ml",
      description: "Bebidas",
      ingredient: "",
      price: 4.5,
      additional: "",
      image: "p18.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Fanta Uva Lata 350ml",
      description: "Bebidas",
      ingredient: "",
      price: 4.5,
      additional: "",
      image: "p3.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Fanta Laranja Lata 350ml",
      description: "Bebidas",
      ingredient: "",
      price: 4.5,
      additional: "",
      image: "p5.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Sprite Lata 350ml",
      description: "Bebidas",
      ingredient: "",
      price: 4.5,
      additional: "",
      image: "p4.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Coca Cola Zero Lata 350ml",
      description: "Bebidas",
      ingredient: "",
      price: 4.5,
      additional: "",
      image: "p19.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
    {
      name: "Coca Cola Lata 350ml",
      description: "Bebidas",
      ingredient: "",
      price: 4.5,
      additional: "",
      image: "p6.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 4,
      measureUnid_id: 59,
      visibleApp: true,
    },
  ]);
};
